# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post title', max_length=250, unique_for_date='-created_time'),
        ),
    ]
